---
version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gosec
    - govet
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        Rule not allowed packages:
          files:
            - .*
          deny:
            - pkg: notexist
              desc: notexist is not allowed or blacklisted
    dupl:
      threshold: 100
    funlen:
      lines: 140
      statements: 52
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - hugeParam
        - appendCombine
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        rangeValCopy:
          sizeThreshold: 1024
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: G306
      - linters:
          - funlen
        path: cmd/root\.go
      - linters:
          - gosec
        text: G404
      - linters:
          - dupl
        path: pkg/terraform/*
      - linters:
          - dupl
        path: pkg/terragrunt/*
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
